version: "2.1"
services:
   todo:
     build: 
       context: .
       dockerfile: Dockerfile-todo
     #image: jack/todo-demo:1.0.1
     image: jack/todo-demo:1.0.0
     ports:
       - "8080:8080"
     depends_on:
       mysql:
         condition: service_healthy
     container_name: todo
     networks: 
       - mynet1
   
   mysql:
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: tododb
       MYSQL_USER: user
       MYSQL_PASSWORD: pass 
     build: 
       context: .
       dockerfile: Dockerfile-mysql
     image: jack/mysql:5.6
     container_name: mysql
     networks: 
       - mynet1

networks:
  mynet1:
    driver: bridge
